const Contact =require=require('../models/contact.model');

const getContacts =async(req,res)=>{
        try {
            const contacts = await Contact.find({});
            res.status(200).json(contacts);
        } catch (error) {
            res.status(500).json({ message: error.message });
        } 
};

const getContact = async (req,res)=>{
    try {
        const { id } = req.params;
        const contact = await Contact.findById(id);
        if (!contact) {
            return res.status(404).json({ message: "Contact not found" });
        }
        res.status(200).json(contact);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

const createContact =async (req,res)=>{
    try {
        const contact = await Contact.create(req.body);
        res.status(201).json(contact);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

const updateContact =async(req,res)=>{
    try {
        const { id } = req.params;
        const contact = await Contact.findByIdAndUpdate(id, req.body, {
            new: true, // Return the updated document
            runValidators: true, // Validate before updating
        });
        if (!contact) {
            return res.status(404).json({ message: "Contact not found" });
        }
        res.status(200).json(contact);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

const deleteContact=async(req,res)=>{
    try {
        const { id } = req.params;
    
        const contact = await Contact.findByIdAndDelete(id);
    
        if (!contact) {
          return res.status(404).json({ message: "Contact not found" });
        }
    
        res.status(200).json({ message: "Contact deleted successfully" });
      } catch (error) {
        res.status(500).json({ message: error.message });
      }
};

module.exports={
     getContacts,
     getContact,
     createContact,
     updateContact,
     deleteContact
}